CREATE TABLE T_CONTA (
   NUMERO BIGINT NOT NULL,
   PESSOA_ID BIGINT NOT NULL,
   SALDO DECIMAL NOT NULL,
   DATA_CRIACAO DATE NOT NULL,
   DATA_FECHAMENTO DATE,
   PRIMARY KEY (NUMERO)
);

CREATE TABLE T_MOVIMENTACAO (
   ID BIGINT NOT NULL AUTO_INCREMENT,
   TIPO VARCHAR(10) NOT NULL,
   DATA DATETIME NOT NULL,
   CONTA_ORIGEM BIGINT NOT NULL,
   CONTA_DESTINO BIGINT NOT NULL,
   VALOR DECIMAL NOT NULL,
   PRIMARY KEY (ID),
    FOREIGN KEY (CONTA_ORIGEM) REFERENCES T_CONTA (NUMERO),
    FOREIGN KEY (CONTA_DESTINO) REFERENCES T_CONTA (NUMERO)
);
